config/routes.rb
Rails.application.routes.draw do
  resources :estanteria
  #devise_for :users
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  get 'inicio/index'
  root :to => "inicio#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/principal' => 'principal#index', as: :user_root # creates user_root_path
  namespace :user do
    root 'principal#index' # creates user_root_path
  end
  
  get 'search' => "search#search"
  post 'search' => "search#search"
  put 'search', to: 'search#actualizar', as: 'lista_canciones'
  
  put '/estanteria', to: 'estanteria#actualizar', as: 'actualizar'
  patch '/estanteria', to: 'estanteria#borrar', as: 'borrar'
  
  get 'peliculas' => 'peliculas#index'
  get 'listas' => 'listas#index'
  get 'novedades' => 'novedades#index'
  #put 'estanteria' => "estanteria#actualizar"
  
  #match '/estanteria', to: 'estanteria#actualizar', via: 'put'
  
  #post '/principal' => "search#search"  
end

app/views/listas/index.html.erb
<!doctype html>

<html class="no-js" lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Declivia</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <%= stylesheet_link_tag 'principal_login', media: "all" %>
        <%= stylesheet_link_tag 'sidebar_login', media: "all" %>
        <%= stylesheet_link_tag 'peliculas', media: "all" %>
        <%= stylesheet_link_tag 'musica', media: "all" %>
        <%= stylesheet_link_tag 'modal_pelicula', media: "all" %>
        <%= stylesheet_link_tag 'modal_serie', media: "all" %>
        <%= stylesheet_link_tag 'modal_juego', media: "all" %>
        <%= stylesheet_link_tag 'modal_musica', media: "all" %>
        <%= stylesheet_link_tag 'estanteria', media: "all" %>
        <%= javascript_include_tag 'application' => true %>
        <%= javascript_include_tag 'principal' => true %>
        <%= csrf_meta_tags %>

        <script>
          $('.dropdown-toggle').dropdown();
        </script>
                    
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top navbarColor" role="navigation">
                <!-- El logotipo y el icono que despliega el menú se agrupan para mostrarlos mejor en los dispositivos móviles -->
            <div class="container-fluid">    
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!--<span class="navbar-brand" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>-->
                    <a class="navbar-brand" style="color: white;" href="#menu-toggle" id="menu-toggle"><span class="glyphicon glyphicon-list" aria-hidden="true"></span></a>
                    <a class="navbar-brand" style="color: white;" href="/principal">Declivia</a>
                    <a class="navbar-brand" style="color: white; font-size: 15px;" href="/novedades">Novedades</a>
                    <a class="navbar-brand" style="color: white; font-size: 15px;" href="/estanteria">Mi estantería</a>
                    <a class="navbar-brand" style="color: white; font-size: 15px;" href="/listas">Listas</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <div class="navbar-right">
                        <a class="navbar-brand" style="color: white; font-size: 15px;" data-toggle="collapse" href="#searchToggle"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Búsqueda</a>
                        <span class="navbar-brand" style="color: white; font-size: 15px;">
                          <% if current_user %>
                               
                          <% end %>
                        </span>
                        <div class="dropdown navbar-brand">
                          <% if current_user %>
                          <a class="dropdown-toggle" type="button" id="dropdownLink" data-toggle="dropdown" style="color: white; font-size: 15px; text-decoration:none;">
                            Bienvenido <%= current_user.user %>
                            <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownLink">
                            <li role="presentation"><%= link_to 'Mi cuenta',edit_user_registration_path %></li>
                            <li role="presentation" class="divider"></li>
                            <li role="presentation"><%= link_to 'Desconectar', destroy_user_session_path, method: :delete %></li>
                          </ul>
                          <% end %>
                        </div>
                    </div>     
                </div>  
            </div>
        </nav>
        <div id="searchToggle" class="collapse">
          <div class="container-fluid tam-search">
            <%= form_tag({:controller => "search", :action => "search"}, :method => "post") do |f|%>
            <div class="input-group lugar-search" id="adv-search" style="margin-top: 50px;">
             <%= text_field_tag "titulo", "", type:"text", :required => "required", class:"form-control", placeholder:"Busca una película, disco, juego..." %> 
             <!--<input type="text" class="form-control" placeholder="Busca una película, disco, juego..." />-->
             <div class="input-group-btn">
                 <div class="btn-group" role="group">
                     <div class="dropdown dropdown-lg">
                         <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></button>
                         <div class="dropdown-menu dropdown-menu-right" role="menu">
                           <div class="form-horizontal" role="form">
                            <div class="form-group">
                              <label for="filter">Buscar por</label>
                              <fieldset>
                                <%= radio_button_tag "id", "Peliculas", true %>
                                <label for="id_Peliculas">Películas</label>
                                <%= radio_button_tag "id", "Series"%>
                                <label for="id_Series">Series</label>
                                <%= radio_button_tag "id", "Musica"%>
                                <label for="id_Musica">Música</label>
                                <%= radio_button_tag "id", "Juegos"%>
                                <label for="id_Juegos">Juegos</label>
                              </fieldset>                              
                            </div>
                          </div>
                         </div>
                     </div> 
                     <span class="input-group-btn">
                      <%= button_tag(:class => "btn btn-primary") do%>
                         <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                      <%end%>
                      <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                     </span>
                 </div>
             </div>
            <% end %>
            </div>
         </div>
        </div>
        <div id="wrapper" class="toggled">
            <div class="container-fluid">
            <!-- Sidebar -->
                <div id="sidebar-wrapper">
                    <ul class="sidebar-nav">
                        <li>
                            <p></p>
                        </li>
                        <li>
                            <a href="/principal"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>  Inicio</a>
                        </li>
                        <li>
                            <a href="/estanteria"><span class="glyphicon glyphicon-book" aria-hidden="true"></span>  Mi estantería</a>
                        </li>
                        <li>
                            <a href="/novedades"><span class="glyphicon glyphicon-fire" aria-hidden="true"></span>  Novedades</a>
                        </li> 
                        <li>
                            <a data-toggle="collapse" href="#searchToggle"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>  Búsqueda</a>
                        </li>
                        <li>
                            <a href="/listas"><span class="glyphicon glyphicon-list" aria-hidden="true"></span>  Listas</a>
                        </li>
                        <li>
                            <a href="/users/edit"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>  Perfil</a>
                        </li>
                        <hr class="hr-separator"/>    
                        <li style="font-size: x-small; color: #999999; line-height: 20px;">
                            <a href="">Preguntas frecuentes</a>
                        </li>
                        <li style="font-size: x-small; color: #999999; line-height: 20px;">
                            <a href="">Qué es Declivia</a>
                        </li>
                        <li style="font-size: x-small; color: #999999; line-height: 20px;">
                            <a href="">Quiénes somos</a>
                        </li>
                        <li style="font-size: x-small; color: #999999; line-height: 20px;">
                            <a href="">Privacidad y condiciones</a>
                        </li>
                        <li style="font-size: x-small; color: #999999; line-height: 20px;">
                            <a href="">Política de cookies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="jumbotron text-center tam-jumbo color-jumbo">
                Descargar: 
                <%= link_to "CSV", peliculas_path(format: "csv") %> |
                <%= link_to "Excel", peliculas_path(format: "xls") %>
            </div>
        </div>
      </div>
    </body>

    <script>
      $("#menu-toggle").click(function(e) {
        e.preventDefault();
      $("#wrapper").toggleClass("toggled");
      });
    </script>
    
</html>