config/routes.rb
Rails.application.routes.draw do
  resources :estanteria
  #devise_for :users
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  get 'inicio/index'
  root :to => "inicio#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/principal' => 'principal#index', as: :user_root # creates user_root_path
  namespace :user do
    root 'principal#index' # creates user_root_path
  end
  
  get 'search' => "search#search"
  post 'search' => "search#search"
  put 'search', to: 'search#actualizar', as: 'lista_canciones'
  
  put '/estanteria', to: 'estanteria#actualizar', as: 'actualizar'
  patch '/estanteria', to: 'estanteria#borrar', as: 'borrar'
  
  get 'peliculas' => 'peliculas#index'
  get 'listas' => 'listas#index'
  get 'novedades' => 'novedades#index'
  #put 'estanteria' => "estanteria#actualizar"
  
  #match '/estanteria', to: 'estanteria#actualizar', via: 'put'
  
  #post '/principal' => "search#search"  
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
    
  end
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/views/inicio/index.html.erb
<!doctype html>

<html class="no-js" lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Declivia</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <%= stylesheet_link_tag 'principal', media: "all" %>
        <%= stylesheet_link_tag 'sidebar', media: "all" %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <!-- , 'data-turbolinks-track' iba en la línea de arriba-->
        <%= csrf_meta_tags %>
                    
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <!-- El logotipo y el icono que despliega el menú se agrupan para mostrarlos mejor en los dispositivos móviles -->
            <div class="container-fluid">    
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" style="color: white;" href="#menu-toggle" id="menu-toggle"><span class="glyphicon glyphicon-list" aria-hidden="true"></span></a>
                    <a class="navbar-brand" style="color: white;" href="">Declivia</a>
                    <a class="navbar-brand" style="color: white; font-size: 15px;" href="/novedades">Novedades</a>
                    <a class="navbar-brand" style="color: white; font-size: 15px;" href="">¿Qué es Declivia?</a>                    
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <div class="navbar-form navbar-right">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalLogin">Iniciar Sesión</button> 
                    </div>     
                </div>  
            </div>
        </nav>
        <div id="wrapper" class="toggled">
            <div class="container-fluid">
            <!-- Sidebar -->
                <div id="sidebar-wrapper">
                    <ul class="sidebar-nav">
                        <li>
                            <p></p>
                        </li>
                        <li>
                            <a href=""><span class="glyphicon glyphicon-home" aria-hidden="true"></span>  Inicio</a>
                        </li>
                        <li>
                            <a href="/novedades"><span class="glyphicon glyphicon-fire" aria-hidden="true"></span>  Novedades</a>
                        </li> 
                        <!--
                        <li>
                            <a href=""><span class="glyphicon glyphicon-search" aria-hidden="true"></span>  Búsqueda</a>
                        </li>
                        <li>
                            <a href=""><span class="glyphicon glyphicon-list" aria-hidden="true"></span>  Listas</a>
                        </li>-->
                        <hr class="hr-separator"/>    
                        <li style="font-size: x-small; color: #999999; line-height: 20px;">
                            <a href="">Preguntas frecuentes</a>
                        </li>
                        <li style="font-size: x-small; color: #999999; line-height: 20px;">
                            <a href="">Qué es Declivia</a>
                        </li>
                        <li style="font-size: x-small; color: #999999; line-height: 20px;">
                            <a href="">Quiénes somos</a>
                        </li>
                        <li style="font-size: x-small; color: #999999; line-height: 20px;">
                            <a href="">Privacidad y condiciones</a>
                        </li>
                        <li style="font-size: x-small; color: #999999; line-height: 20px;">
                            <a href="">Política de cookies</a>
                        </li>  
                    </ul>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="jumbotron text-center tam-jumbo color-jumbo">
                <h1>¡Bienvenidos a Declivia!</h1>
                <p>Tu biblioteca digital donde podrás tener organizada tu colección de películas, discos y videojuegos. </p>
                <div class="panel panel-primary color-registro tam-registro" style="background-color: #9AE6FC;">
                    <div class="panel-heading">
                        Regístrate
                    </div>
                    <div class="panel-body">
                        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                            <%= devise_error_messages! %>
                            <div class="login-element text-left">
                              <label for="user">Nombre de usuario</label>
                              <div class="input-group">
                                  <%= f.text_field :user, :autofocus => true, :class => "form-control", :placeholder => 'Usuario', :required=> true%>
                                  <span class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
                              </div>
                            </div>
                            <div class="login-element text-left">
                              <label for="user">Tu E-Mail</label>
                              <div class="input-group">
                                  <%= f.email_field :email, :autofocus => true, :class => "form-control", :placeholder => 'Correo Electrónico', :required=> true%>
                                  <span class="input-group-addon">
                                      <span class="glyphicon glyphicon-envelope"></span>
                                  </span>
                              </div>
                            </div>
                            <div class="login-element text-left">
                              <label for="user">
                                  Contraseña
                                  <% if @minimum_password_length %>
                                    <em>(mínimo <%= @minimum_password_length %> caracteres)</em>
                                  <% end %><br />
                              </label>
                              <div class="input-group">
                                  <%= f.password_field :password, :class=> "form-control", :placeholder=> 'Password', :required=> true %>
                                  <span class="input-group-addon">
                                      <span class="glyphicon glyphicon-lock"></span>
                                  </span>
                              </div>
                            </div>
                            <div class="login-element text-left">
                              <label for="user">Confirmar contraseña</label>
                              <div class="input-group">
                                  <%= f.password_field :password_confirmation, :class=> "form-control", :placeholder=> 'Password', :required=> true %>
                                  <span class="input-group-addon">
                                      <span class="glyphicon glyphicon-lock"></span>
                                  </span>
                              </div>
                            </div>
                            <div class="login-element"><p></p></div>
                            <%= f.submit "Crear mi cuenta", :class=> "btn btn-lg btn-block btn-primary login" %>
                            <div class="login-element text-left">
                                Pulsando el botón "Crear mi cuenta" estoy aceptando las
                                <a href="#">Condiciones de uso</a>
                                , la 
                                <a href="#">Política de privacidad</a>
                                 y la 
                                <a href="#">Política de Cookies</a>.
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="modalLogin" tabindex="-1">
          <div class="modal-dialog modal-sm">

          <!-- Modal content-->
          <div class="modal-content color-registro" style="background-color: #9AE6FC;">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <center><h3 style="font-weight:bold;">DECLIVIA</h3></center>
            </div>
            <div class="modal-body">
              <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                  <div class="input-group login-element">
                    <%= f.text_field :user, autofocus: true, :class => "form-control", :placeholder => 'Usuario', :required=> true%>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
                  </div>
                  <div class="input-group login-element">
                    <%= f.password_field :password, :class=> "form-control", :placeholder=> 'Password', :required=> true %>
                    <span class="input-group-addon">
                      <span class="glyphicon glyphicon-lock"></span>
                    </span>
                  </div>
                  <div class="checkbox login-element">
                    <% if devise_mapping.rememberable? -%>
                    <b><label><%= f.check_box :remember_me %><span>Recordar mis datos</span></label>
                    <% end %>
                    <span>·</span>
                    <%= link_to "¿Olvidaste tu contraseña?", new_password_path(resource_name) %>
                    <div class="login-element"></div>
                  </div>
                  <%= f.submit "Iniciar Sesión", :class=> "btn btn-lg btn-block btn-primary" %>
                <% end %>
            </div>
            <div class="modal-footer u-textCenter">
              <label>
                  ¿No tienes cuenta?
                  <a href="">Regístrate</a>
              </label>
            </div>
          </div>
        </div>
      </div>
    </body>
    
    <!-- Menu Toggle Script -->
    <script>
      $("#menu-toggle").click(function(e) {
        e.preventDefault();
      $("#wrapper").toggleClass("toggled");
      });
    </script>
    
</html>